const mongoose=require('mongoose');
const productSchema=new mongoose.Schema(
    {
        name:
        {
            type:String,
            required:true
        },
        description:
        {
            type:String
        },
        price:
        {
            type:Number,
            required:true
        },
        category:
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Category',
            required:true
        },
        stock:
        {
            type:Number
        },
        sold:
        {
            type:Number,
            default:0
        },
        photo:
        {
            data:Buffer,
            contentType:String
        }
    },
    {timestamps:true}
);
var Product=mongoose.model('Product',productSchema);
module.exports=Product;